name: create VDB

on:
  create:
    branches: ["*"]
  
  workflow_dispatch:

jobs:
  # This workflow contains a job to manage VDB and SelfService container life-cycle
  manage_vdbs:
    environment:
      name: delphix-engine
    runs-on: ubuntu-latest
    container: delphix/dxtoolkit:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Set dxtools.conf
        run: |
          mkdir /config
          echo {\"data\":[{\"hostname\" : \"Delphix\",\"ip_address\" : \"3.90.84.185\",\"username\" : \"admin\",\"password\" : \"admin\",\"port\" : \"80\",\"default\" : \"false\",\"encrypted\" : \"false\",\"timeout\" : \"60\"}]} > /config/dxtools.conf
                  
       # Criando VDB
      - name: Set dxtools.conf
        run: dx_provision_vdb -d Delphix -group SQLServer_TARGET -sourcename DS_AdventureWorksLT2019 -targetname  ${{ github.ref }} -dbname  ${{ github.ref }} -environment MSSQLSERVER_2019 -type mssql -envinst MSSQLSERVER
